version: '3'

services:
  myapp:
    container_name: doroga_vishneve
    image: python:3.8-slim
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && python ./telegram/main.py"
    restart: always

